"""Add sub_level

Revision ID: c1b7db21b677
Revises: 5dee625453da
Create Date: 2025-05-21 20:48:39.219910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import api


# revision identifiers, used by Alembic.
revision: str = 'c1b7db21b677'
down_revision: Union[str, None] = '5dee625453da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_level', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='subscriptionlevel'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sub_level')

    # ### end Alembic commands ###
